// Fünf weitere Karten in den acht noch ausstehenden Kategorien.
const NC=(category,title,summary,detail,media,sources=[],extra={})=>({category,title,...(summary?{summary}:{}),detail,media,sources,...extra});
const Q=(label,url)=>S(label,url);

window.KARTEN.push(
  NC("Philosophische Begriffe","Aufhebung","Etwas wird beendet, bewahrt und auf eine neue Stufe gebracht.",["Hegel nutzt alle drei Bedeutungen des Verbs aufheben. Eine Bestimmung verliert ihre selbständige Geltung; ihr Gehalt bleibt im folgenden Begriff erhalten und wird dort verändert.","Aufhebung ist kein versöhnlicher Mittelweg. Der neue Begriff entsteht aus dem bestimmten Widerspruch des vorherigen."],[C("Georg Wilhelm Friedrich Hegel portrait","Hegel")],[Q("Hegel: Wissenschaft der Logik","https://www.projekt-gutenberg.org/hegel/logik1/logik1.html")]),
  NC("Philosophische Begriffe","Habitus","Erworbene Neigungen, durch die Menschen wahrnehmen und handeln.",["Bei Pierre Bourdieu entsteht der Habitus aus Lebensbedingungen, Erziehung und wiederholter Praxis. Er wirkt in Geschmack, Körperhaltung, Erwartungen und spontanen Entscheidungen.","Der Begriff verbindet Gesellschaft und individuelles Handeln: Menschen improvisieren, doch ihr Sinn für das Mögliche trägt die Geschichte ihrer sozialen Position in sich."],[C("Pierre Bourdieu portrait","Pierre Bourdieu")],[Q("Encyclopaedia Britannica: Pierre Bourdieu","https://www.britannica.com/biography/Pierre-Bourdieu")]),
  NC("Philosophische Begriffe","Intentionalität","Bewusstsein ist stets auf etwas gerichtet.",["Brentano bezeichnete die Beziehung auf einen Gegenstand als Kennzeichen psychischer Akte. Husserl machte sie zum Ausgangspunkt der Phänomenologie: Wahrnehmen, Erinnern, Urteilen und Hoffen geben ihre Gegenstände jeweils anders.","Der Gegenstand muss real nicht vorhanden sein. Auch eine Erwartung, eine Zahl oder eine erfundene Figur kann gemeint sein."],[C("Edmund Husserl 1910","Edmund Husserl")],[Q("Stanford Encyclopedia of Philosophy: Intentionality","https://plato.stanford.edu/entries/intentionality/")]),
  NC("Philosophische Begriffe","Schleier des Nichtwissens","Grundsätze werden gewählt, ohne die eigene spätere Stellung zu kennen.",["In John Rawls' Ursprungssituation kennen die Beteiligten ihre Klasse, Begabungen, Religion, Herkunft und Lebensziele nicht. Allgemeines Wissen über Gesellschaft bleibt verfügbar.","Der Schleier entfernt Zufallsvorteile aus der Wahl gemeinsamer Regeln. Er ist ein Prüfverfahren für faire Institutionen."],[C("John Rawls portrait","John Rawls")],[Q("Stanford Encyclopedia of Philosophy: Original Position","https://plato.stanford.edu/entries/original-position/")]),
  NC("Philosophische Begriffe","Wu wei","Handeln ohne erzwungenes Eingreifen.",["Im Daodejing meint wu wei keine Untätigkeit. Eine Handlung folgt den Bedingungen so genau, dass sie ohne angestrengte Beherrschung, Übermaß und unnötige Reibung auskommt.","Politisch richtet sich der Begriff gegen kleinteilige Kontrolle; persönlich gegen ein Wollen, das jede Lage gewaltsam formt."],[C("Daodejing Mawangdui manuscript","Daodejing-Manuskript")],[Q("Chinese Text Project: Dao De Jing","https://ctext.org/dao-de-jing")]),

  NC("Künstler und drei Werke","Gwen John","The Convalescent · Dorelia in a Black Dress · A Corner of the Artist’s Room",["John baute Figuren und Räume aus gedämpften Farbschichten. Kleine Verschiebungen von Blick, Haltung und Licht tragen die Spannung. Ihre konzentrierte Malerei wurde lange von der öffentlichen Rolle ihres Bruders Augustus verdeckt."],[C("Gwen John The Convalescent","The Convalescent"),C("Gwen John Dorelia black dress","Dorelia in a Black Dress"),C("Gwen John artist room Paris","A Corner of the Artist’s Room")],[Q("Tate: Gwen John","https://www.tate.org.uk/art/artists/gwen-john-1366")],{works:["The Convalescent, um 1923–24","Dorelia in a Black Dress, um 1903–04","A Corner of the Artist’s Room in Paris, 1907–09"]}),
  NC("Künstler und drei Werke","Evelyn De Morgan","Medea · Night and Sleep · The Gilded Cage",["De Morgan verband präzise Figurenmalerei mit Allegorien über Krieg, Gefangenschaft, geistige Freiheit und die Lage von Frauen. Ihre leuchtende Oberfläche trägt oft einen scharfen politischen Gedanken."],[C("Evelyn De Morgan Medea","Medea"),C("Evelyn De Morgan Night and Sleep","Night and Sleep"),C("Evelyn De Morgan Gilded Cage","The Gilded Cage")],[Q("De Morgan Collection","https://www.demorgan.org.uk/collection/")],{works:["Medea, 1889","Night and Sleep, 1878","The Gilded Cage, 1919"]}),
  NC("Künstler und drei Werke","Edmonia Lewis","Forever Free · The Death of Cleopatra · The Old Arrow Maker",["Lewis arbeitete in Rom im weißen Marmor der neoklassizistischen Bildhauerei. Sie gab historischen und biblischen Stoffen eine eigene politische Reichweite und behauptete sich als Frau afroamerikanischer und indigener Herkunft im internationalen Kunstbetrieb."],[C("Edmonia Lewis Forever Free","Forever Free"),C("Edmonia Lewis Death Cleopatra","The Death of Cleopatra"),C("Edmonia Lewis Old Arrow Maker","The Old Arrow Maker")],[Q("Smithsonian American Art Museum: Edmonia Lewis","https://americanart.si.edu/artist/edmonia-lewis-2914")],{works:["Forever Free, 1867","The Death of Cleopatra, 1876","The Old Arrow Maker, 1872"]}),
  NC("Künstler und drei Werke","Léon Spilliaert","Selbstbildnis vor dem Spiegel · Schwindel · Mondhelle Marine",["Spilliaert setzte Tusche, Kreide und verdünnte Farbe ein, um leere Promenaden, steile Räume und das eigene Gesicht in psychische Landschaften zu verwandeln. Linien und dunkle Flächen erzeugen die Wirkung."],[C("Leon Spilliaert self portrait mirror 1908","Selbstbildnis"),C("Leon Spilliaert Vertigo 1908","Schwindel"),C("Leon Spilliaert moonlit marine","Mondhelle Marine")],[Q("Royal Museums of Fine Arts Belgium: Spilliaert","https://fine-arts-museum.be/en/the-artists/leon-spilliaert")],{works:["Self-Portrait in Front of the Mirror, 1908","Vertigo, 1908","Moonlit Marine, um 1900"]}),
  NC("Künstler und drei Werke","Käthe Kollwitz","Frau mit totem Kind · Weberzug · Die Mütter",["Kollwitz entwickelte aus Radierung, Lithografie, Holzschnitt und Plastik eine Bildsprache für Trauer, Armut, Widerstand und körperliche Nähe. Die Figuren gewinnen ihre Kraft aus Haltung und Gewicht."],[C("Käthe Kollwitz Woman with Dead Child","Frau mit totem Kind"),C("Käthe Kollwitz March Weavers","Weberzug"),C("Käthe Kollwitz Mothers 1922","Die Mütter")],[Q("Käthe Kollwitz Museum Köln","https://www.kollwitz.de/sammlung")],{works:["Frau mit totem Kind, 1903","Weberzug, 1897","Die Mütter, 1922–23"]}),

  NC("Erste Sätze großer Romane","It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness …",null,["Charles Dickens eröffnet A Tale of Two Cities (1859) mit einer langen Folge von Gegensätzen. Der Roman spielt in London und Paris vor und während der Französischen Revolution. Charles Darnay, Sydney Carton und Lucie Manette geraten in eine Geschichte von Haft, politischer Gewalt, Ähnlichkeit und Opfer."],[C("A Tale of Two Cities first edition title page","Erstausgabe von 1859")],[Q("Project Gutenberg: A Tale of Two Cities","https://www.gutenberg.org/ebooks/98")],{kind:"quote"}),
  NC("Erste Sätze großer Romane","Mrs Dalloway said she would buy the flowers herself.",null,["Virginia Woolfs Mrs Dalloway (1925) folgt Clarissa Dalloway an einem Junitag durch London und verbindet ihre Vorbereitungen für eine Abendgesellschaft mit den Erfahrungen des Kriegsveteranen Septimus Warren Smith. Gedanken, Erinnerungen und Straßengeräusche wechseln zwischen den Figuren."],[C("Mrs Dalloway first edition cover","Erstausgabe von 1925")],[Q("British Library: Mrs Dalloway","https://www.bl.uk/works/mrs-dalloway")],{kind:"quote"}),
  NC("Erste Sätze großer Romane","Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed.",null,["Ulysses (1922) beginnt am Morgen des 16. Juni 1904 im Martello Tower bei Dublin. James Joyce führt Stephen Dedalus, Leopold Bloom und Molly Bloom durch einen einzigen Tag; Aufbau und Motive beziehen sich auf Homers Odyssee."],[C("Ulysses 1922 first edition","Erstausgabe von Ulysses")],[Q("Project Gutenberg: Ulysses","https://www.gutenberg.org/ebooks/4300")],{kind:"quote"}),
  NC("Erste Sätze großer Romane","This is the saddest story I have ever heard.",null,["Ford Madox Fords The Good Soldier (1915) wird von John Dowell erzählt. Erst nach und nach zeigt sich, wie wenig er die beiden Ehepaare verstanden hat, über die er berichtet. Zeitsprünge und Korrekturen machen seine Unsicherheit zur Form des Romans."],[C("The Good Soldier Ford first edition","Erstausgabe von 1915")],[Q("Project Gutenberg: The Good Soldier","https://www.gutenberg.org/ebooks/2775")],{kind:"quote"}),
  NC("Erste Sätze großer Romane","Я человек больной… Я злой человек.",null,["Der Erzähler von Dostojewskis Aufzeichnungen aus dem Kellerloch (1864) stellt sich als kranker, boshafter Mensch vor. Aus seinem Petersburger Zimmer greift er Vernunftoptimismus und die Vorstellung berechenbarer Interessen an; anschließend erzählt er Szenen eigener Demütigung und Grausamkeit."],[C("Dostoevsky Notes from Underground edition","Frühe Ausgabe")],[Q("Wikisource: Записки из подполья","https://ru.wikisource.org/wiki/Записки_из_подполья_(Достоевский)")],{kind:"quote"}),

  NC("Seltene Musikstile","Dhrupad · Nordindien",null,["Dhrupad ist eine alte Form nordindischer Kunstmusik. Ein langsamer, rhythmisch freier Alap entfaltet den Raga Ton für Ton; im gebundenen Teil tragen Pakhawaj-Trommel und ein strenger Gedichttext die Form."],[Y("HpknENIsIMo","Gundecha Brothers · Dhrupad")],[Q("Sangeet Natak Akademi","https://www.sangeetnatak.gov.in/")]),
  NC("Seltene Musikstile","Shōmyō · Japan",null,["Shōmyō bezeichnet buddhistischen Ritualgesang. Lange Melismen, gleitende Tonhöhen und festgelegte Formeln ordnen die Rezitation; die Schulen Tendai und Shingon bewahren verschiedene Linien."],[Y("Qe7Rer-q0eg","Shōmyō · Japan Society")],[Q("Japan Society","https://japansociety.org/")]),
  NC("Seltene Musikstile","Paghjella · Korsika",null,["Die Paghjella wird meist von drei Männerstimmen gesungen. Bassu, seconda und terza setzen nacheinander ein und bilden enge, raue Zusammenklänge mit reich verzierten Oberstimmen."],[Y("gd3uR-wr1yI","Paghjella aus Korsika")],[Q("UNESCO: Cantu in paghjella","https://ich.unesco.org/en/USL/cantu-in-paghjella-00173")]),
  NC("Seltene Musikstile","Gnawa · Marokko",null,["Gnawa-Musik verbindet responsorialen Gesang, die dreisaitige Basslaute Guembri und eiserne Qarqaba-Kastagnetten. In der nächtlichen Lila-Zeremonie gliedern Melodien, Farben und Räucherstoffe eine Folge ritueller Abschnitte."],[Y("t9ZmTodoSII","Gnawa-Ensemble")],[Q("UNESCO: Gnawa","https://ich.unesco.org/en/RL/gnawa-01170")]),
  NC("Seltene Musikstile","Launeddas · Sardinien",null,["Die Launeddas besteht aus drei gleichzeitig gespielten Rohrpfeifen. Zirkularatmung hält den Klang ohne Unterbrechung; zwei Pfeifen bilden Bordun und Grundgerüst, die dritte führt bewegliche Melodien."],[Y("BzWITU3L-F0","Luigi Lai spielt Launeddas")],[Q("Sardegna Cultura","https://www.sardegnacultura.it/")]),

  NC("Vergessene Komponisten","Emilie Mayer · Sinfonie Nr. 7 f-Moll",null,["Mayer führt kurze Motive sicher durch das Orchester. Unruhige Begleitfiguren, scharf gesetzte Bläsereinsätze und abrupte harmonische Wendungen geben der Sinfonie ihr Profil.","Sie leitete in Berlin eigene Konzerte. Die Siebte verdient Aufmerksamkeit, weil sie die Sinfonik des 19. Jahrhunderts um eine eigenständige, handwerklich souveräne Stimme erweitert."],[Y("3GaUyM8gr_Q","Emilie Mayer · Sinfonie Nr. 7"),C("Emilie Mayer portrait","Emilie Mayer")],[Q("MUGI: Emilie Mayer","https://mugi.hfmt-hamburg.de/artikel/Emilie_Mayer.html")]),
  NC("Vergessene Komponisten","Ethel Smyth · The Wreckers",null,["Smyth verbindet schroffe Chorblöcke, bewegliche Orchesterfarben und eine Liebestragödie an der kornischen Küste. Meer, religiöser Fanatismus und Gewalt werden musikalisch zu handelnden Kräften.","Die Oper verdient neue Aufführungen, weil sie dramatisch geschlossen ist und eine markante englische Antwort auf das Musiktheater um 1900 gibt."],[Y("dj9U3QLTd1c","The Wreckers · Ouvertüre"),C("Ethel Smyth portrait","Ethel Smyth")],[Q("British Library: Ethel Smyth","https://www.bl.uk/people/ethel-smyth")]),
  NC("Vergessene Komponisten","Margaret Bonds · Montgomery Variations",null,["Bonds verwandelt das Spiritual I Want Jesus to Walk with Me in sieben Variationen. Jede erhält eine politische Widmung; Spiritual, Blues, Kontrapunkt und Orchesterklang bleiben eng verbunden.","Das Werk gehört ins Repertoire, weil es die Bürgerrechtsbewegung in einer großen sinfonischen Form reflektiert und Bonds' Gespür für Variation und Klang zeigt."],[Y("ereaXUDie-A","Montgomery Variations"),C("Margaret Bonds composer","Margaret Bonds")],[Q("Library of Congress: Margaret Bonds","https://www.loc.gov/item/ihas.200152702/")]),
  NC("Vergessene Komponisten","Rebecca Clarke · Viola Sonata",null,["Clarke nutzt die dunkle Mittellage der Viola, weite Linien, Flageoletts und eine Klavierstimme, die Farbe und Rhythmus gleichberechtigt trägt. Wiederkehrende Motive verbinden die drei Sätze.","Die Sonate gehört ins Kernrepertoire, weil sie instrumentale Kenntnis und formale Konzentration mit einer unverwechselbaren Harmonik verbindet."],[Y("kyhWWyDHIfM","Rebecca Clarke · Viola Sonata"),C("Rebecca Clarke composer portrait","Rebecca Clarke")],[Q("Rebecca Clarke Society","https://rebeccaclarke.org/")]),
  NC("Vergessene Komponisten","Florence Price · Sinfonie Nr. 3 c-Moll",null,["Price verbindet sinfonische Entwicklung mit Juba-Rhythmen, Bluesfärbungen und fein geschichteten Orchesterfarben. Das Scherzo gewinnt seine Form aus dem Tanz.","Die Dritte verdient Aufmerksamkeit als reifes Werk einer Komponistin, deren Partituren nach ihrem Tod jahrzehntelang kaum zugänglich waren und das Bild der amerikanischen Sinfonik erweitern."],[Y("jI6qZFrsDnw","Florence Price · Sinfonie Nr. 3"),C("Florence Price composer portrait","Florence Price")],[Q("University of Arkansas: Florence Price","https://libraries.uark.edu/specialcollections/fprice/")]),

  NC("Großartige Bilder und Design","W. E. B. Du Bois · Data Portraits",null,["Für die Pariser Weltausstellung 1900 entwarf Du Bois mit seinem Team Diagramme zum Leben afroamerikanischer Menschen. Spiralen, Fächer und Farbflächen verwandeln statistische Daten in eine radikale visuelle Grammatik."],[C("WEB Du Bois data portrait 1900","Data Portrait"),C("Du Bois Georgia Negro chart","Diagramm zur Ausstellung")],[Q("Library of Congress: Du Bois data portraits","https://www.loc.gov/pictures/collection/anedub/")]),
  NC("Großartige Bilder und Design","Talwin Morris · Buchgestaltung für Blackie & Son",null,["Morris ordnete Pflanzenlinien, Rechtecke und kleine Farbfelder zu klaren Einbänden. Seine Bücher zeigen, wie der Glasgow Style auf preiswerte Serienproduktion übertragen wurde."],[C("Talwin Morris book cover","Bucheinband"),C("Talwin Morris Blackie binding","Einband für Blackie & Son")],[Q("V&A: Talwin Morris","https://www.vam.ac.uk/articles/talwin-morris")]),
  NC("Großartige Bilder und Design","Margaret Macdonald Mackintosh · The Mysterious Garden",null,["Gesso, Metall, Perlen und Farbe bilden eine flache, zugleich körperliche Oberfläche. Figuren wachsen aus Ornamenten hervor; Material und Bild lassen sich kaum trennen."],[C("Margaret Macdonald Mackintosh Mysterious Garden","The Mysterious Garden"),C("Margaret Macdonald Mackintosh gesso panel","Gesso-Detail")],[Q("National Galleries Scotland: Mackintosh","https://www.nationalgalleries.org/art-and-artists/artists/margaret-macdonald-mackintosh")]),
  NC("Großartige Bilder und Design","Daum Frères · Cameo-Glas",null,["Mehrschichtiges Glas wurde geätzt, geschnitten, emailliert und teilweise mit eingeschmolzenen Pulvern modelliert. Landschaften und Pflanzen entstehen aus dem Material selbst."],[C("Daum Nancy cameo glass vase","Cameo-Glasvase"),C("Daum Freres landscape vase","Landschaftsvase")],[Q("Musée des Beaux-Arts de Nancy","https://musee-des-beaux-arts.nancy.fr/")]),
  NC("Großartige Bilder und Design","Aubrey Beardsley · The Peacock Skirt",null,["Beardsley verteilt Schwarz und Weiß in großen, präzisen Flächen. Pfauenmuster, Profile und der fast leere Raum machen die Illustration zu einer eigenständigen Komposition."],[C("Aubrey Beardsley Peacock Skirt 1894","The Peacock Skirt"),C("Beardsley Salome Peacock Skirt","Detail")],[Q("V&A: Aubrey Beardsley","https://www.vam.ac.uk/articles/aubrey-beardsley")]),

  NC("Märchen und Sagen in ethnografischen Quellen","Die Ermordung Tuwhakararos · Māori",null,["Tuwhakararo wird bei einem Besuch in einer fremden Siedlung getötet. Seine Mutter Apakura ruft in einem Klagegesang die Verwandten zur Vergeltung; Whakatau führt den Angriff auf das Haus der Gegner.","George Grey veröffentlichte die überlieferte Erzählung 1855. Die Textdatei enthält den vollständigen historischen Wortlaut des Kapitels."],[C("Maori waka historical","Māori-Waka"),C("Maori meeting house carving","Versammlungshaus")],[Q("George Grey: Polynesian Mythology","https://www.sacred-texts.com/pac/grey/grey08.htm")],{original:{label:"Vollständiger Originaltext · Grey (1855)",file:"texts/maui-mahuika.txt",source:"https://www.sacred-texts.com/pac/grey/grey08.htm"}}),
  NC("Märchen und Sagen in ethnografischen Quellen","Die Schildkröte mit der schönen Tochter · Efik",null,["Eine Schildkröte verbirgt ihre Tochter, nachdem der König erklärt hat, nur ein reicher Mann dürfe ein außergewöhnlich schönes Mädchen heiraten. Der Königssohn entdeckt sie.","Elphinstone Dayrell veröffentlichte die in Südnigeria aufgezeichnete Fassung 1910. Die Anwendung lädt die ganze Erzählung beim Öffnen aus der öffentlichen Transkription."],[C("African spurred tortoise","Schildkröte"),C("Calabar Nigeria 1900","Calabar")],[Q("Dayrell: Folk Stories from Southern Nigeria","https://sacred-texts.com/afr/fssn/fsn03.htm")],{original:{label:"Vollständiger Originaltext · Dayrell (1910)",source:"https://sacred-texts.com/afr/fssn/fsn03.htm"}}),
  NC("Märchen und Sagen in ethnografischen Quellen","Die Frau mit zwei Häuten · Efik",null,["Eine Frau besitzt eine schöne und eine hässliche Haut. Ihre eifersüchtige Mitfrau beobachtet den Wechsel und verrät das Geheimnis dem gemeinsamen Mann.","Elphinstone Dayrell veröffentlichte die in Südnigeria aufgezeichnete Fassung 1910. Die Datei enthält die Erzählung vollständig."],[C("Calabar woman historical","Frau aus Calabar"),C("Calabar Nigeria historical","Calabar")],[Q("Dayrell: Folk Stories from Southern Nigeria","https://sacred-texts.com/afr/fssn/fsn05.htm")],{original:{label:"Vollständiger Originaltext · Dayrell (1910)",file:"texts/woman-two-skins-efik.txt",source:"https://sacred-texts.com/afr/fssn/fsn05.htm"}}),
  NC("Märchen und Sagen in ethnografischen Quellen","Warum die Fledermaus nachts fliegt · Efik",null,["Eine Fledermaus bringt eine Ratte durch eine falsche Kochanweisung in tödliche Gefahr und versucht anschließend, sich der Verantwortung zu entziehen.","Dayrells Sammlung von 1910 gibt die Erzählung samt der abschließenden Erklärung wieder. Die Textdatei enthält den ganzen historischen Wortlaut."],[C("African bat","Fledermaus"),C("Calabar Nigeria 1900","Calabar")],[Q("Dayrell: Folk Stories from Southern Nigeria","https://sacred-texts.com/afr/fssn/fsn09.htm")],{original:{label:"Vollständiger Originaltext · Dayrell (1910)",file:"texts/bat-night-efik.txt",source:"https://sacred-texts.com/afr/fssn/fsn09.htm"}}),
  NC("Märchen und Sagen in ethnografischen Quellen","Die Zaubertrommel · Efik",null,["Eine Schildkröte erhält eine Trommel, die auf Wunsch Essen hervorbringt. Gier, öffentliches Vorführen und ein Regelverstoß verwandeln die Gabe in eine Gefahr.","Elphinstone Dayrell veröffentlichte die Erzählung 1910. Die Textdatei gibt sie vom ersten bis zum letzten Satz wieder."],[C("African slit drum historical","Trommel"),C("Calabar Nigeria 1900","Calabar")],[Q("Dayrell: Folk Stories from Southern Nigeria","https://sacred-texts.com/afr/fssn/fsn06.htm")],{original:{label:"Vollständiger Originaltext · Dayrell (1910)",file:"texts/magic-drum-efik.txt",source:"https://sacred-texts.com/afr/fssn/fsn06.htm"}}),

  NC("Sagengestalten, Legenden und Märchen weltweit","Inanna · Sumer",null,["Inanna, Göttin von Macht, Sexualität und Krieg, passiert auf dem Weg in die Unterwelt sieben Tore und legt an jedem ein Zeichen ihrer Herrschaft ab. Ereškigal lässt sie töten und an einen Haken hängen.","Boten erwirken ihre Rückkehr, doch jemand muss ihren Platz einnehmen. Inanna bestimmt Dumuzi; dessen Schwester Geštinanna teilt später seinen Aufenthalt. Der Wechsel verbindet die Erzählung mit dem jahreszeitlichen Rhythmus des Kultes."],[C("Burney Relief Inanna","Inanna"),C("Inanna Ishtar cylinder seal","Siegelbild")],[Q("ETCSL: Inana's descent","https://etcsl.orinst.ox.ac.uk/section1/tr141.htm")]),
  NC("Sagengestalten, Legenden und Märchen weltweit","Ame-no-Uzume · Japan",null,["Als Amaterasu sich in eine Felsenhöhle zurückzieht, verschwindet das Licht. Die Götter hängen Spiegel und Juwelen an einen Baum.","Ame-no-Uzume tanzt auf einem umgedrehten Trog; das Gelächter macht Amaterasu neugierig. Als sie hinausschaut, wird sie herausgezogen. Uzumes Aufführung verbindet Komik, Ritual und die Wiederkehr des Lichts."],[C("Ame no Uzume Amaterasu cave","Ame-no-Uzume"),C("Uzume Japanese print","Uzumes Tanz")],[Q("Kojiki · Sacred Texts","https://sacred-texts.com/shi/kj/index.htm")]),
  NC("Sagengestalten, Legenden und Märchen weltweit","Väinämöinen · Finnland und Karelien",null,["Väinämöinen ist Sänger, Zauberer und Hauptheld des Kalevala. Seine Macht liegt im Wissen um Ursprungslieder. Aus dem Kiefer eines riesigen Hechts baut er die erste Kantele; sein Spiel bewegt Menschen, Tiere und Natur.","Elias Lönnrot formte die Figur aus verschiedenen karelischen Gesängen zu einem epischen Helden. Am Ende fährt Väinämöinen in einem kupfernen Boot fort und lässt Kantele und Lieder zurück."],[C("Gallen Kallela Väinämöinen","Väinämöinen"),C("Väinämöinen kantele","Kantele")],[Q("Project Gutenberg: Kalevala","https://www.gutenberg.org/ebooks/5186")]),
  NC("Sagengestalten, Legenden und Märchen weltweit","Koschtschei der Todlose · Ostslawische Märchen",null,["Koschtschei ist ein dürrer Zauberer, der Frauen entführt und Schätze bewacht. Sein Tod liegt außerhalb seines Körpers: oft in einer Nadel, die in Ei, Ente, Hase und Truhe verborgen ist.","Der Held muss die verschachtelten Behälter finden; mit der Nadel stirbt Koschtschei. Mehrere Märchen verbinden das Motiv mit Iwan Zarewitsch, Marja Morewna oder der Froschprinzessin."],[C("Koschei Deathless Vasnetsov","Koschtschei"),C("Ivan Bilibin Koschei","Bilibins Illustration")],[Q("Wikisource: Russian Folk-Tales","https://en.wikisource.org/wiki/Russian_Folk-Tales")]),
  NC("Sagengestalten, Legenden und Märchen weltweit","Popocatépetl und Iztaccíhuatl · Mexiko",null,["Eine verbreitete Legendenfassung erzählt von der Prinzessin Iztaccíhuatl und dem Krieger Popocatépetl. Eine falsche Todesmeldung tötet ihre Hoffnung; der Heimkehrer trägt sie in die Berge und wacht bei ihr.","Die Vulkane werden als liegende Frau und kniender Wächter gelesen. Frühe koloniale Quellen belegen Namen und Kulte der Berge; die geschlossene Liebesgeschichte zirkuliert in späteren Varianten."],[C("Popocatepetl Iztaccihuatl view","Die beiden Vulkane"),C("Iztaccihuatl sleeping woman","Iztaccíhuatl")],[Q("Instituto Nacional de Antropología e Historia","https://www.inah.gob.mx/")])
);
